// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTqkT4iht_Ar14dfMEBlWt57ZlLudf5Vs',
    appId: '1:1074363599283:web:906aa90f12d4c70f6ea3c6',
    messagingSenderId: '1074363599283',
    projectId: 'attendance-adhimix',
    authDomain: 'attendance-adhimix.firebaseapp.com',
    storageBucket: 'attendance-adhimix.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAx2ISQ67vGTxW16Y1K-535RqCV2CEyQ20',
    appId: '1:1074363599283:android:239815d7319568db6ea3c6',
    messagingSenderId: '1074363599283',
    projectId: 'attendance-adhimix',
    storageBucket: 'attendance-adhimix.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdQPJ1u_ctE1mckWO7chB50GAEoNXELYs',
    appId: '1:1074363599283:ios:d496171178738d726ea3c6',
    messagingSenderId: '1074363599283',
    projectId: 'attendance-adhimix',
    storageBucket: 'attendance-adhimix.appspot.com',
    iosBundleId: 'com.example.absensiAdhimix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdQPJ1u_ctE1mckWO7chB50GAEoNXELYs',
    appId: '1:1074363599283:ios:d496171178738d726ea3c6',
    messagingSenderId: '1074363599283',
    projectId: 'attendance-adhimix',
    storageBucket: 'attendance-adhimix.appspot.com',
    iosBundleId: 'com.example.absensiAdhimix',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTqkT4iht_Ar14dfMEBlWt57ZlLudf5Vs',
    appId: '1:1074363599283:web:6e18b2a10105a9626ea3c6',
    messagingSenderId: '1074363599283',
    projectId: 'attendance-adhimix',
    authDomain: 'attendance-adhimix.firebaseapp.com',
    storageBucket: 'attendance-adhimix.appspot.com',
  );
}
